export const Skill_data: Skill_data[] = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Json Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Tauri",
    Image: "/tauri.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Nigx",
    Image:
      "https://i0.wp.com/thinkground.studio/wp-content/uploads/2019/04/190415_Nginx-Logo.png?fit=423%2C401&ssl=1",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Go",
    Image: "/go.png",
    width: 60,
    hight: 60,
  },
  {
    skill_name: "Gin gonic",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];

export const Skills_line_1: Skill_data[] = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 45,
    hight: 45,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 45,
    hight: 45,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Sass",
    Image: "/sass.svg",
    width: 80,
    hight: 80,
  },
];

export const Skills_line_2: Skill_data[] = [
  {
    skill_name: "Bootstrap",
    Image: "/bootstrap.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 30,
    hight: 30,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 45,
    hight: 45,
  },
  {
    skill_name: "Json Web Token",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 45,
    hight: 45,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 50,
    hight: 50,
  },
];

export const Skills_line_3: Skill_data[] = [
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 35,
    hight: 35,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 45,
    hight: 45,
  },
]

export const Skills_line_4: Skill_data[] = [
  {
    skill_name: "stripe",
    Image: "/stripe.webp",
    width: 45,
    hight: 45,
  },
  {
    skill_name: "paypal",
    Image: "/paypal.png",
    width: 35,
    hight: 35,
  },
  {
    skill_name: "mercagopago",
    Image: "/mercadopago.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "sellix",
    Image: "/sellix.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "binance",
    Image: "/binance.png",
    width: 40,
    hight: 40,
  },
]



export const Project: Project_data[] = [
  {
    title: "Hilos y perlas ",
    video_key: "v3LJMcWbcDQ",
    say_xi: "Freelance project for client 👟",
    say_xi_blog:
      "eCommerce project dedicated to the sale of sneakers and accessories. Authentication performed with NextAuth including providers such as Google, Facebook and Apple. Payment platform used: Mercado Pago.",
    technology_feature: [
      "Material UI",
      "React",
      "Nextjs",
      "TypeScript",
      "NextAuth",
      "MongoDB",
    ],

    about_this_app:
      "Connection with mongoose - mongodb, authentication middlewares, data fetching with SWR, cookie management with CookieJS, front-end forms and validations with React-use-form, alerts with NotiStack, login validations with Google Recaptcha and respective rules from the backend, encrypted passwords with BcryptJS.",
    design_blog:
      "Layout design in figma and code 100% developed by me. 💖",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@emotion/react",
      "@emotion/styled",
      "@mui/icons-material",
      "@mui/material",
      "@types/node",
      "@types/react",
      "@types/react-dom",
      "axios",
      "bcryptjs",
      "eslint",
      "eslint-config-next",
      "jsonwebtoken",
      "mongoose",
      "next",
      "next-auth",
      "react",
      "react-dom",
      "react-hook-form",
      "typescript",
      "-project under development, more dependencies can be added..."
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "",
    backend_dowload_link:
      "",
    project_image: "/hpyecommerce.png",
    project_blog:
      "eCommerce project dedicated to the sale of sneakers and accessories. Authentication performed with NextAuth including providers such as Google, Facebook and Apple. Payment platform used: Mercado Pago.",
    Type: "Fullstack",
    indevelopment: true,
  },
  {
    title: "Modern Portfolio 2023",
    video_key: "v3LdJM2cWbcDQ",
    say_xi: "My Portfolio 2023 ☘️",
    say_xi_blog:
      "This is my portfolio, it contains a beautiful interface and animations with Framer motion, basic NextAuth authentication with some providers.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Nextjs",
      "TypeScript",
      "Framer Motion",
      "NextAuth"
    ],

    about_this_app:
      "Global status manager: Redux Toolkit, Authentication providers: Google, Instagram, Facebook and GitHub, custom animations with Tailwind and Framer Motion.",
    design_blog:
      "Code 100% developed by me.💖",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "@types/node",
      "@types/react",
      "@types/react-dom",
      "@types/react-spinkit",
      "autoprefixer",
      "axios",
      "eslint",
      "eslint-config-next",
      "framer-motion",
      "maath",
      "next",
      "next-auth",
      "postcss",
      "react",
      "react-dom",
      "react-redux",
      "react-spinkit",
      "tailwindcss",
      "typescript",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "",
    backend_dowload_link:
      "",
    project_image: "/portfolio.png",
    project_blog:
      "This is my portfolio, it contains a beautiful interface and animations with Framer motion, basic NextAuth authentication with some providers.",
    Type: "FullStack",
    indevelopment: false,
  },
  {
    title: "Kill a Server",
    video_key: "SyUh9is7G8w",
    say_xi: "Freelance project for foreign client 🌏",
    say_xi_blog:
      "Project dedicated to information security, with a robust backend with strong security measures. Authentication performed with NextAuth including providers such as Discord, Github and Facebook. Payment platform used: Sellix ",
    technology_feature: [
      "Material UI",
      "React",
      "Nextjs",
      "TypeScript",
      "NextAuth",
      "MongoDB",
    ],
    about_this_app:
      "Connection with mongoose - mongodb, authentication middlewares, data fetching with SWR, cookie management with CookieJS, front-end forms and validations with React-use-form, alerts with NotiStack, login validations with Google Recaptcha and respective rules from the backend, encrypted passwords with BcryptJS.",
    design_blog: "Layout design in figma and code 100% developed by me. 💖",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@emotion/react",
      "@emotion/styled",
      "@fortawesome/fontawesome-svg-core",
      "@fortawesome/free-solid-svg-icons",
      "@fortawesome/react-fontawesome",
      "@mui/material",
      "@types/node",
      "@types/react",
      "@types/react-dom",
      "aos",
      "axios",
      "bcryptjs",
      "eslint",
      "eslint-config-next",
      "js-cookie",
      "mongoose",
      "next",
      "next-auth",
      "notistack",
      "react",
      "react-dom",
      "react-google-recaptcha",
      "react-hook-form",
      "react-intersection-observer",
      "react-slick",
      "slick-carousel",
      "swr",
      "typescript",
      "use-count-up",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/SyUh9is7G8w",
    githhub_link: "https://github.com/nachopedraza1/killserver-app/tree/main",
    frontend_dowload_link:
      "https://github.com/nachopedraza1/killserver-app/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/killserver.png",
    project_blog:
      "Project dedicated to information security, with a robust backend with strong security measures. Authentication performed with NextAuth including providers such as Discord, Github and Facebook. Payment platform used: Sellix ",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Damage Developers",
    video_key: "v3LJMcWb12cDQ",
    say_xi: "Freelancer Entrepreneurship 🌏",
    say_xi_blog:
      "Personal entrepreneurship as a Freelancer web developer, using the latest technologies in the market.",
    technology_feature: [
      "Material UI",
      "React",
      "Nextjs",
      "TypeScript",
      "CSS"
    ],

    about_this_app:
      "Basic UI layout in figma, form control with Formik, integrated WhasatsApp API for queries or orders, Material UI with some CSS for styling.",
    design_blog:
      "Layout design in figma and code 100% developed by me.💖 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@emotion/react",
      "@emotion/styled",
      "@mui/icons-material",
      "@mui/material",
      "@types/node",
      "@types/react",
      "@types/react-dom",
      "eslint",
      "eslint-config-next",
      "formik",
      "next",
      "react",
      "react-dom",
      "react-intersection-observer",
      "react-slick",
      "slick-carousel",
      "typescript",
      "use-count-up",
      "yup",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "",
    backend_dowload_link:
      "",
    project_image: "/damagedevs.png",
    project_blog:
      "Personal entrepreneurship as a Freelancer web developer, using the latest technologies in the market.",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Belgrano eSports",
    video_key: "yF1124oJ7wzvWY",
    say_xi: "Freelance project for large association. 💖",
    say_xi_blog:
      "Project made for a big soccer association, in this case made for the eSports area, the site contains an administration panel where you can manage the site, for example: Upload new matches, upload results, view contenders, modify teams, upload rivals, among many other things.",
    technology_feature: [
      "Material UI",
      "React",
      "Redux",
      "JavaScript",
      "Firebase",
      "SASS"
    ],

    about_this_app:
      "It contains full CRUD, Firebase database, store with Redux Toolkit, authentication providers such as Facebook, Twitter and GitHub, data with Instagram API, Twitch API and Twitter API, alerts with SweetAlert2, Styles with material Ui and own styles with SCSS.",
    design_blog:
      "Layout design in figma and code 100% developed by me.💖 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@emailjs/browser",
      "@emotion/react",
      "@emotion/styled",
      "@mui/icons-material",
      "@mui/material",
      "@mui/styled-engine-sc",
      "@mui/x-data-grid",
      "@mui/x-date-pickers",
      "@reduxjs/toolkit",
      "aos",
      "axios",
      "firebase",
      "moment",
      "react",
      "react-dom",
      "react-owl-carousel",
      "react-redux",
      "react-router-dom",
      "react-twitch-embed",
      "react-twitter-widgets",
      "sass",
      "sweetalert2",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "",
    backend_dowload_link:
      "",
    project_image: "/belgranoesports.png",
    project_blog:
      "Project made for a big soccer association, in this case made for the eSports area, the site contains an administration panel where you can manage the site, for example: Upload new matches, upload results, view contenders, modify teams, upload rivals, among many other things.",
    Type: "Next js 13",
    indevelopment: false,
  },
  /* {
    title: "Deliveroo Mobile App",
    video_key: "AxQ_Eli8gtk",
    say_xi: "Xi from my first mobile app 📱",
    say_xi_blog:
      "ReactNative First Project With Expo CLI Conatain Google AUthentication Contain Basic RestApi and Google Maps functionality ",
    technology_feature: [
      "Tailwind",
      "React Native",
      "Redux",
      "Type Script",
      "Expo",
      "Node js",
      "Express js",
      "Postger sql",
    ],

    about_this_app:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    design_blog: "Desing From PapaReact YouTube Channel",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case we use Yarn and since this project was developed using expo we can also use the expo-cli to install the dependencies.",
    package: [
      "expo",
      "react-native-gesture-handler",
      "react-native-heroicons",
      "react-native-maps",
      "react-native-progress",
      "react-native-safe-area-context",
      "react-native-screens",
      "react-native-svg",
      "react-redux",
      "typescript",
      "nativewind",
      "expo-splash-screen",
      "@react-navigation/native",
      "@react-native-masked-view/masked-view",
      "@react-native-async-storage/async-storage",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo_Mobile.apk/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "",
    project_blog:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    Type: "React Native",
    project_Img_Mobile: [
      "/deliveroo1.jpg",
      "/roo2.jpg",
      "/roo3.jpg",
      "/roo4.jpg",
      "/roo5.jpg",
    ],
    indevelopment: false,
  }, */
  {
    title: "Guides Prodotol Mu",
    video_key: "R190bxY4U4wPg",
    say_xi: "Freelance project for a client in my city 📱",
    say_xi_blog:
      "Project dedicated to the world of MMO videogames, specifically MU Online, an informative site about the different guides of the videogame, it contains more than 40 pages written and consumed from a JSON object.",
    technology_feature: [
      "Material UI",
      "React",
      "Redux",
      "TypeScript",
    ],

    about_this_app:
      "All the photos were optimized and made in adobe photoshop, Redux was used to manage the state of the guides, as for the inputs they are controlled by native code without external libraries. The typewriter effect is controlled by the typewriter-effect library. The carousel is realized with react-slick-carousel. SASS for custom styles and to maintain order.",
    design_blog: "Desing From Realworld ChatGPT",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm ",
    package: [
      "@emotion/react",
      "@emotion/styled",
      "@mui/icons-material",
      "@mui/material",
      "@reduxjs/toolkit",
      "moment",
      "react",
      "react-dom",
      "react-redux",
      "react-router-dom",
      "react-slick",
      "sass",
      "slick-carousel",
      "typewriter-effect",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "",
    backend_dowload_link: "",
    project_image: "/protocol.png",
    project_blog:
      "Project dedicated to the world of MMO videogames, specifically MU Online, an informative site about the different guides of the videogame, it contains more than 40 pages written and consumed from a JSON object.",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Teslo Shop (Clone)",
    video_key: "R90bxY4UwPg",
    say_xi: "Xello My Frends 💚",
    say_xi_blog:
      "This is my First AI Project data Coming From Opend AI , You can asked like RealTime Chat GPT   ",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],

    about_this_app:
      "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
    design_blog: "Desing From Realworld ChatGPT",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm ",
    package: [
      "@reduxjs/toolkit",
      "@uiball/loaders",
      "firebase",
      "firebase-admin",
      "nextjs-progressbar",
      "openai",
      "react-firebase-hooks",
      "react-icons",
      "react-redux",
      "react-simple-typewriter",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Chat_GPT4/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/tesloshop.png",
    project_blog:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
    Type: "Next js 13",
    indevelopment: true,
  },
  {
    title: "Bebo Design",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Xi Form Responsive Food Project🤤",
    say_xi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/bebodesign.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "DenBots",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Xi Form Responsive Food Project🤤",
    say_xi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/denbots.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
  },
  {
    title: "Aorus with React (Clone)",
    video_key: "6wzf2ho-kzI",
    say_xi: "Hello my friend! 👋🏼",
    say_xi_blog:
      "This is a Normal 3 js Responsive Profiol Website Constain Starts Mode , Background Music , Day and Light Mode , Contain youtube emb video like youtube Mobile Responsive desing Base on Vite ",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Threes js",
      "Framer Motion",
    ],
    about_this_app:
      "This Responsive  Website is Make for showcase Project Profile ",
    design_blog:
      "very basic desing from My Friends , and I ReModified It All Code & Desing by Me ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I use npm beacuse We use older npm package .",
    package: [
      " maath",
      " @react-three/fiber",
      " @emailjs/browser",
      " framer-motion",
      " @react-three/fiber ",
      " @reduxjs/toolkit ",
      " react-router-dom",
      " react-tilt",
      " react-simple-typewriter",
      " react-icons",
      " react-spinkit",
      " react-vertical-timeline-component",
      " three",
    ],
    conclusion_blog:
      "As I said at the beginning, this is a great project for begginers and even for those who are not new to React . I bealive this is a grat project to have in a resume or portfolio. I am very happy with the app and I hope you will enjoy it as well.",
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Profiol_2/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/aorus.png",
    project_blog:
      "Morden Profiol Wbsite With Javascript | React | Tailwind css | Responsive Website profiol desing.",
    Type: "React",
    indevelopment: false,
  },
  {
    title: "Aorus Vanilla Shop (Clone)",
    video_key: "cLKsNVSyPMM",
    say_xi: "Hello my Friends 🎉",
    say_xi_blog:
      "Fullstack Social Media Project With  React , Tailwind css and My First Node js express Server ☘️ ",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Node js",
      "Express js",
    ],
    about_this_app:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
    design_blog:
      "Basic Desing From Youtube and I Modified That Desing All Code By Me an My Own Desing ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@mui/icons-material",
      "@reduxjs/toolkit",
      "formik",
      "javascript-time-ago",
      "jwt-decode",
      "material-ui-popup-state",
      "pusher-js",
      "react-dropzone",
      "react-easy-crop",
      "react-icons",
      "react-redux",
      "react-router-dom",
      "redux-persist",
      "swiper",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/cLKsNVSyPMM",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
    project_image: "/venexclone.png",
    project_blog:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    Type: "React",
    indevelopment: false,
  },
  {
    title: "Fantasias ",
    video_key: "cLKsNVSyPMM",
    say_xi: "Hello my Friends 🎉",
    say_xi_blog:
      "Fullstack Social Media Project With  React , Tailwind css and My First Node js express Server ☘️ ",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Node js",
      "Express js",
    ],
    about_this_app:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
    design_blog:
      "Basic Desing From Youtube and I Modified That Desing All Code By Me an My Own Desing ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@mui/icons-material",
      "@reduxjs/toolkit",
      "formik",
      "javascript-time-ago",
      "jwt-decode",
      "material-ui-popup-state",
      "pusher-js",
      "react-dropzone",
      "react-easy-crop",
      "react-icons",
      "react-redux",
      "react-router-dom",
      "redux-persist",
      "swiper",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/cLKsNVSyPMM",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
    project_image: "/fantasias.png",
    project_blog:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    Type: "React",
    indevelopment: false,
  },
  {
    title: "Profiol Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: ["Golang", "Gin", "Mongo db", "JWT"],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/goserver.png",
    project_blog:
      "My First Go , Gin Server , Basic CRUD Go Server With Mongodb",
    Type: "server",
    indevelopment: true,
  },
  {
    title: "ShoeEcommerce Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "JWT",
      "Stripe",
    ],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      " User authentication Google auth , Facebook auth , Nike Auth ..more , Mind leven CRUD functionality",
    Type: "server",
    indevelopment: false,
  },
  {
    title: "FoodOrder & AdminDashboard",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      "User authentication , Graphql  Mind leven CRUD functionality , Google auth , Facebook auth , Fastfood Auth,",
    Type: "server",
    indevelopment: false,
  },
  {
    title: "Deliveroo Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Postger sql",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "/n2.png",
    project_blog:
      "Node js Express With Postger Sql ,FireBase FireStore  CRUD functionality",
    Type: "server",
    indevelopment: false,
  },
];

export const colour: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
];

/*
  {
    title: "",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    project_blog: "",
    Type: "Next js 13",
    indevelopment: false,
  },
*/
